server:
    port: 8090

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: borrowing-service
          uri: lb://borrowing-service
          predicates:
            - Path=/borrowings/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance-info-replication-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: api-gateway:${server.port}